# Generated by Django 5.0.2 on 2024-08-29 11:40

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('title_uz', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='news/image', verbose_name='image')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description')),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newscategory', verbose_name='category')),
                ('tags', models.ManyToManyField(to='news.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
            },
        ),
    ]
