# Generated by Django 5.0.2 on 2024-03-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan sana'),
        ),
    ]
