# Generated by Django 5.0.2 on 2024-02-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Bunday foydalanuvchi nomiga ega foydalanuvchi allaqachon mavjud.'}, help_text='Majburiy. 150 yoki undan kam belgi. Faqat harflar, raqamlar va @/./+/-/_.', max_length=50, unique=True),
        ),
    ]
