# Generated by Django 5.0.2 on 2024-07-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='image link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='direction',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='direction'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='patronymic'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with this username already exists.'}, help_text='Mandatory. 150 characters or less. Only letters, numbers and @/./+/-/_.', max_length=50, unique=True),
        ),
    ]
