# Generated by Django 5.0.2 on 2024-11-19 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 12, 8, 55, 765568, tzinfo=datetime.timezone.utc)),
        ),
    ]
