# Generated by Django 5.0.2 on 2024-02-24 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUpProjects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='sarlavha')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='startup/images', verbose_name='Rasm')),
                ('content', models.TextField(verbose_name="Loyiha ta'rifi")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Karusel', 'verbose_name_plural': 'Karusellar'},
        ),
        migrations.AlterField(
            model_name='carousel',
            name='content',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='matn 1'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='content2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='matn 2'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='carousel', verbose_name='Rasm'),
        ),
    ]
