# Generated by Django 5.0.2 on 2024-02-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_startupprojects_alter_carousel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprojects',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='mavjudligi'),
        ),
    ]
