# Generated by Django 5.0.2 on 2024-02-26 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_startupprojects_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentedStudents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='ism')),
                ('last_name', models.CharField(max_length=150, verbose_name='Familiya')),
                ('patronymic', models.CharField(max_length=150, verbose_name='Otasining ismi')),
                ('teacher_full_name', models.CharField(max_length=255, verbose_name="Talaba o'qituvchisi")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Talaba haqida ma'lumot")),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Iqtidorli talaba',
                'verbose_name_plural': 'Iqtidorli talabalar',
            },
        ),
        migrations.AlterModelOptions(
            name='startupprojects',
            options={'verbose_name': 'Start Up loyiha', 'verbose_name_plural': 'Start Up loyihalar'},
        ),
    ]
