# Generated by Django 5.0.2 on 2024-02-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_talentedstudents_alter_startupprojects_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentedstudents',
            name='talent_type',
            field=models.CharField(choices=[('PRESIDENT', 'Prezident'), ('STATE', 'Davlat stipendiatlar'), ('TALENT', 'Iqtidorli talabalar')], default='TALENT', max_length=15),
        ),
    ]
