# Generated by Django 5.0.2 on 2024-02-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_talentedstudents_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentedstudents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='talent-tudent/images'),
        ),
    ]
