# Generated by Django 5.0.2 on 2024-03-04 05:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_talentedstudents_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doc_type', models.PositiveSmallIntegerField(choices=[(1, 'Buyruqlar'), (2, 'Nizomlar')])),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/doc/files')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='talentedstudents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='talent-tudent/images', verbose_name='Talaba rasmi'),
        ),
        migrations.AlterField(
            model_name='talentedstudents',
            name='teacher_full_name',
            field=models.CharField(max_length=255, verbose_name="O'qituvchi F.I.SH"),
        ),
    ]
