# Generated by Django 5.0.2 on 2024-03-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_documents_alter_talentedstudents_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name_plural': "Me'yoriy hujjatlar"},
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Buyruqlar'), (2, 'Nizomlar')], verbose_name='Hujjat turi'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to='uploads/doc/files', verbose_name='fayl'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='hujjat nomi'),
        ),
    ]
