# Generated by Django 5.0.2 on 2024-03-11 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_documents_options_alter_documents_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='doc_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 6, 22, 11, 608371, tzinfo=datetime.timezone.utc)),
        ),
    ]
