# Generated by Django 5.0.2 on 2024-03-11 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_competition_alter_carousel_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 9, 59, 1, 820882, tzinfo=datetime.timezone.utc)),
        ),
    ]
