# Generated by Django 5.0.2 on 2024-04-24 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_competition_options_alter_documents_doc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 5, 9, 59, 528593, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='talentedstudents',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='mavjudligi'),
        ),
        migrations.AlterField(
            model_name='talentedstudents',
            name='talent_type',
            field=models.CharField(choices=[('PRESIDENT', 'Prezident stipendiatlar'), ('STATE', 'Davlat stipendiatlar'), ('TALENT', 'Iqtidorli talabalar')], default='TALENT', max_length=15, verbose_name='iqtidor turi'),
        ),
    ]
