# Generated by Django 5.0.2 on 2024-04-24 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_documents_doc_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 5, 19, 54, 47942, tzinfo=datetime.timezone.utc)),
        ),
    ]
