# Generated by Django 5.0.2 on 2024-05-20 07:12

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_documents_doc_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Carousel', 'verbose_name_plural': 'Carousels'},
        ),
        migrations.AlterModelOptions(
            name='startupprojects',
            options={'verbose_name': 'startup project', 'verbose_name_plural': 'startup projects'},
        ),
        migrations.AlterModelOptions(
            name='talentedstudents',
            options={'verbose_name': 'Talent student', 'verbose_name_plural': 'talent students'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='content2_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='matn 2'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='content2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='matn 2'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='content2_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='matn 2'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='content_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='matn 1'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='content_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='matn 1'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='content_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='matn 1'),
        ),
        migrations.AddField(
            model_name='competition',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='desctiption'),
        ),
        migrations.AddField(
            model_name='competition',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='desctiption'),
        ),
        migrations.AddField(
            model_name='competition',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='desctiption'),
        ),
        migrations.AddField(
            model_name='competition',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='competition',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='competition',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='documents',
            name='file_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='hujjat nomi'),
        ),
        migrations.AddField(
            model_name='documents',
            name='file_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='hujjat nomi'),
        ),
        migrations.AddField(
            model_name='documents',
            name='file_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='hujjat nomi'),
        ),
        migrations.AddField(
            model_name='startupprojects',
            name='content_en',
            field=models.TextField(null=True, verbose_name="Loyiha ta'rifi"),
        ),
        migrations.AddField(
            model_name='startupprojects',
            name='content_ru',
            field=models.TextField(null=True, verbose_name="Loyiha ta'rifi"),
        ),
        migrations.AddField(
            model_name='startupprojects',
            name='content_uz',
            field=models.TextField(null=True, verbose_name="Loyiha ta'rifi"),
        ),
        migrations.AddField(
            model_name='startupprojects',
            name='title_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='startupprojects',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='startupprojects',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='talentedstudents',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name="Talaba haqida ma'lumot"),
        ),
        migrations.AddField(
            model_name='talentedstudents',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Talaba haqida ma'lumot"),
        ),
        migrations.AddField(
            model_name='talentedstudents',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Talaba haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='desctiption'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(upload_to='competition/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 7, 12, 13, 986118, tzinfo=datetime.timezone.utc)),
        ),
    ]
