# Generated by Django 5.0.2 on 2024-05-20 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_carousel_options_alter_startupprojects_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 7, 25, 4, 108421, tzinfo=datetime.timezone.utc)),
        ),
    ]
