# Generated by Django 5.0.2 on 2024-04-24 05:09

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Mazmuni')),
                ('youtube_link', models.CharField(blank=True, null=True, verbose_name='youtube havola')),
                ('course_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=8, verbose_name='Kurs turi')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/course/files', validators=[django.core.validators.FileExtensionValidator(['.pdf', '.doc', '.docx', '.ppt', '.pptx'])], verbose_name='Fayl')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.author', verbose_name='Muallif')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
