# Generated by Django 5.0.2 on 2024-05-20 07:25

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='bio_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='bio_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='course',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='course',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=8, verbose_name='course type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='youtube_link',
            field=models.CharField(blank=True, null=True, verbose_name='youtube link'),
        ),
    ]
